var myProduct = angular.module('myProduct',['ui.router','itemPay']);
myProduct.config(['$stateProvider','$urlRouterProvider',function($stateProvider,$urlRouterProvider){
	$stateProvider
	.state('register',{
		templateUrl:'views/register.html',
		url:'/register'
	})
	.state('login',{
		templateUrl:'views/login.html',
		url:'/login'
	})
	.state('signIn',{
		templateUrl:'views/signIn.html',
		url:'/signIn'
	})
	.state('retrievepd',{
		templateUrl:'views/retrievepd.html',
		url:'/retrievepd'
	})
	.state('right',{
		templateUrl:'views/right.html',
		url:'/right'
	})
	.state('pay',{
		templateUrl:'views/pay.html',
		url:'/pay'
	})
	.state('payments',{
		templateUrl:'views/payments.html',
		url:'/payments'
	})
	.state('deviceinfo',{
		templateUrl:'views/deviceinfo.html',
		url:'/deviceinfo'
	})
	.state('devicemanage',{
		templateUrl:'views/devicemanage.html',
		url:'/devicemanage'
	})
	.state('memberCenter',{
		templateUrl:'views/memberCenter.html',
		url:'/memberCenter'
	})
	.state('mencentinfo',{
		templateUrl:'views/mencentinfo.html',
		url:'/mencentinfo'
	})
	.state('modifyname',{
		templateUrl:'views/modifyname.html',
		url:'/modifyname'
	})
	.state('modifyphone',{
		templateUrl:'views/modifyphone.html',
		url:'/modifyphone'
	})
	.state('modifyphonelist',{
		templateUrl:'views/modifyphonelist.html',
		url:'/modifyphonelist'
	})
	.state('mycapital',{
		templateUrl:'views/mycapital.html',
		url:'/mycapital'
	})
	.state('mydevice',{
		templateUrl:'views/mydevice.html',
		url:'/mydevice'
	})
	$urlRouterProvider.otherwise('register')
}])
